=== pooltogether/v4-draw-results/prize.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://pooltogether.com/prizeAPI.schema.json",
  "title": "PoolTogethers Prize API Schema",
  "description": "Schema for the Prize API",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "address": {
      "type": "string",
      "description": "The lowercase users address",
      "length": 42,
      "examples": ["0xa5c3a513645a9a00cb561fed40438e9dfe0d6a69"]
    },
    "pick": {
      "type": "string",
      "description": "The user's pick for this prize",
      "minLength": 1,
      "maxLength": 42
    },
    "tier": {
      "type": "number",
      "description": "The prize tier of this prize"
    },
    "amount": {
      "type": "string",
      "description": "The amount of the prize",
      "minLength": 1,
      "maxLength": 42
    }
  },
  "required": ["address", "pick", "tier", "amount"]
}

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/113/0x559524b8d5af5292e4ca30b30ea3dc8261e1dea4.json
[
  {
    "address": "0x559524b8d5af5292e4ca30b30ea3dc8261e1dea4",
    "pick": "815",
    "tier": 4,
    "amount": "9999999"
  },
  {
    "address": "0x559524b8d5af5292e4ca30b30ea3dc8261e1dea4",
    "pick": "5598",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x559524b8d5af5292e4ca30b30ea3dc8261e1dea4",
    "pick": "16913",
    "tier": 5,
    "amount": "4999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/1/0x685c66df2a77fbc188371b3470d5a2adca538a03.json
[
  {
    "address": "0x685c66df2a77fbc188371b3470d5a2adca538a03",
    "pick": "684",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0x685c66df2a77fbc188371b3470d5a2adca538a03",
    "pick": "5565",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0x685c66df2a77fbc188371b3470d5a2adca538a03",
    "pick": "6050",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0x685c66df2a77fbc188371b3470d5a2adca538a03",
    "pick": "7732",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0x685c66df2a77fbc188371b3470d5a2adca538a03",
    "pick": "7865",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0x685c66df2a77fbc188371b3470d5a2adca538a03",
    "pick": "9331",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0x685c66df2a77fbc188371b3470d5a2adca538a03",
    "pick": "9922",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0x685c66df2a77fbc188371b3470d5a2adca538a03",
    "pick": "10289",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0x685c66df2a77fbc188371b3470d5a2adca538a03",
    "pick": "11829",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0x685c66df2a77fbc188371b3470d5a2adca538a03",
    "pick": "12916",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0x685c66df2a77fbc188371b3470d5a2adca538a03",
    "pick": "13416",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0x685c66df2a77fbc188371b3470d5a2adca538a03",
    "pick": "14199",
    "tier": 5,
    "amount": "9999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/16/0xc80aa78dc2ad53a0db4653de027d15e5e3ea646a.json
[
  {
    "address": "0xc80aa78dc2ad53a0db4653de027d15e5e3ea646a",
    "pick": "33",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0xc80aa78dc2ad53a0db4653de027d15e5e3ea646a",
    "pick": "3178",
    "tier": 3,
    "amount": "99999999"
  },
  {
    "address": "0xc80aa78dc2ad53a0db4653de027d15e5e3ea646a",
    "pick": "9568",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0xc80aa78dc2ad53a0db4653de027d15e5e3ea646a",
    "pick": "24405",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0xc80aa78dc2ad53a0db4653de027d15e5e3ea646a",
    "pick": "27499",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0xc80aa78dc2ad53a0db4653de027d15e5e3ea646a",
    "pick": "28971",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0xc80aa78dc2ad53a0db4653de027d15e5e3ea646a",
    "pick": "35620",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0xc80aa78dc2ad53a0db4653de027d15e5e3ea646a",
    "pick": "35720",
    "tier": 5,
    "amount": "9999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/177/0x647f6ac07c1ee66c025295e71e45a17f9b0aae94.json
[
  {
    "address": "0x647f6ac07c1ee66c025295e71e45a17f9b0aae94",
    "pick": "2475",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x647f6ac07c1ee66c025295e71e45a17f9b0aae94",
    "pick": "2533",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x647f6ac07c1ee66c025295e71e45a17f9b0aae94",
    "pick": "6853",
    "tier": 5,
    "amount": "4999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/50/0xbad858a0cf09f210fcf35cbf83569178879b47f2.json
[
  {
    "address": "0xbad858a0cf09f210fcf35cbf83569178879b47f2",
    "pick": "271",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0xbad858a0cf09f210fcf35cbf83569178879b47f2",
    "pick": "4253",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xbad858a0cf09f210fcf35cbf83569178879b47f2",
    "pick": "4738",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xbad858a0cf09f210fcf35cbf83569178879b47f2",
    "pick": "6153",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xbad858a0cf09f210fcf35cbf83569178879b47f2",
    "pick": "8065",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0xbad858a0cf09f210fcf35cbf83569178879b47f2",
    "pick": "8435",
    "tier": 4,
    "amount": "9999999"
  },
  {
    "address": "0xbad858a0cf09f210fcf35cbf83569178879b47f2",
    "pick": "9037",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xbad858a0cf09f210fcf35cbf83569178879b47f2",
    "pick": "10578",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xbad858a0cf09f210fcf35cbf83569178879b47f2",
    "pick": "13190",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xbad858a0cf09f210fcf35cbf83569178879b47f2",
    "pick": "20176",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xbad858a0cf09f210fcf35cbf83569178879b47f2",
    "pick": "20473",
    "tier": 4,
    "amount": "9999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/112/0xce84ef39bac143084969bba51a06bdff375f257e.json
[
  {
    "address": "0xce84ef39bac143084969bba51a06bdff375f257e",
    "pick": "4546",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0xce84ef39bac143084969bba51a06bdff375f257e",
    "pick": "33906",
    "tier": 3,
    "amount": "49999999"
  },
  {
    "address": "0xce84ef39bac143084969bba51a06bdff375f257e",
    "pick": "34665",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0xce84ef39bac143084969bba51a06bdff375f257e",
    "pick": "58633",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0xce84ef39bac143084969bba51a06bdff375f257e",
    "pick": "80555",
    "tier": 5,
    "amount": "4999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/110/0xbd5e252a9fbb630c6fddf1c34997361310d35089.json
[
  {
    "address": "0xbd5e252a9fbb630c6fddf1c34997361310d35089",
    "pick": "1806",
    "tier": 3,
    "amount": "49999999"
  },
  {
    "address": "0xbd5e252a9fbb630c6fddf1c34997361310d35089",
    "pick": "5823",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0xbd5e252a9fbb630c6fddf1c34997361310d35089",
    "pick": "11955",
    "tier": 5,
    "amount": "4999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/84/0xab6dc3f226b98b67063e7414ba196744209a65bc.json
[
  {
    "address": "0xab6dc3f226b98b67063e7414ba196744209a65bc",
    "pick": "266",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xab6dc3f226b98b67063e7414ba196744209a65bc",
    "pick": "4273",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xab6dc3f226b98b67063e7414ba196744209a65bc",
    "pick": "6860",
    "tier": 6,
    "amount": "999999"
  }
]
