=== pooltogether/v4-draw-results/prize.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://pooltogether.com/prizeAPI.schema.json",
  "title": "PoolTogethers Prize API Schema",
  "description": "Schema for the Prize API",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "address": {
      "type": "string",
      "description": "The lowercase users address",
      "length": 42,
      "examples": ["0xa5c3a513645a9a00cb561fed40438e9dfe0d6a69"]
    },
    "pick": {
      "type": "string",
      "description": "The user's pick for this prize",
      "minLength": 1,
      "maxLength": 42
    },
    "tier": {
      "type": "number",
      "description": "The prize tier of this prize"
    },
    "amount": {
      "type": "string",
      "description": "The amount of the prize",
      "minLength": 1,
      "maxLength": 42
    }
  },
  "required": ["address", "pick", "tier", "amount"]
}

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/84/0x3fed71848b74b9f3ff26544cad368c082cb31961.json
[
  {
    "address": "0x3fed71848b74b9f3ff26544cad368c082cb31961",
    "pick": "2224",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x3fed71848b74b9f3ff26544cad368c082cb31961",
    "pick": "4843",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0x3fed71848b74b9f3ff26544cad368c082cb31961",
    "pick": "7927",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0x3fed71848b74b9f3ff26544cad368c082cb31961",
    "pick": "12010",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x3fed71848b74b9f3ff26544cad368c082cb31961",
    "pick": "12255",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x3fed71848b74b9f3ff26544cad368c082cb31961",
    "pick": "27736",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0x3fed71848b74b9f3ff26544cad368c082cb31961",
    "pick": "34030",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x3fed71848b74b9f3ff26544cad368c082cb31961",
    "pick": "36665",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x3fed71848b74b9f3ff26544cad368c082cb31961",
    "pick": "42534",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0x3fed71848b74b9f3ff26544cad368c082cb31961",
    "pick": "45643",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0x3fed71848b74b9f3ff26544cad368c082cb31961",
    "pick": "51324",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x3fed71848b74b9f3ff26544cad368c082cb31961",
    "pick": "51925",
    "tier": 6,
    "amount": "999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/84/0x0839519639d7bcc95f64b481ed06e180f258ebb1.json
[
  {
    "address": "0x0839519639d7bcc95f64b481ed06e180f258ebb1",
    "pick": "5923",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x0839519639d7bcc95f64b481ed06e180f258ebb1",
    "pick": "9330",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0x0839519639d7bcc95f64b481ed06e180f258ebb1",
    "pick": "12102",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0x0839519639d7bcc95f64b481ed06e180f258ebb1",
    "pick": "12724",
    "tier": 6,
    "amount": "999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/66/0x0f35af1184282eaffe1304c5f98158175f7f5889.json
[
  {
    "address": "0x0f35af1184282eaffe1304c5f98158175f7f5889",
    "pick": "957",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0x0f35af1184282eaffe1304c5f98158175f7f5889",
    "pick": "1094",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0x0f35af1184282eaffe1304c5f98158175f7f5889",
    "pick": "2443",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x0f35af1184282eaffe1304c5f98158175f7f5889",
    "pick": "5020",
    "tier": 6,
    "amount": "999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/84/0x38742d8717c57dc7ba97e2df7a61e26c3412ffdd.json
[
  {
    "address": "0x38742d8717c57dc7ba97e2df7a61e26c3412ffdd",
    "pick": "8092",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0x38742d8717c57dc7ba97e2df7a61e26c3412ffdd",
    "pick": "24029",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0x38742d8717c57dc7ba97e2df7a61e26c3412ffdd",
    "pick": "30919",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0x38742d8717c57dc7ba97e2df7a61e26c3412ffdd",
    "pick": "43253",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0x38742d8717c57dc7ba97e2df7a61e26c3412ffdd",
    "pick": "43488",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x38742d8717c57dc7ba97e2df7a61e26c3412ffdd",
    "pick": "48611",
    "tier": 6,
    "amount": "999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/84/0xded0e76f559e39ff5dff607b0d58dcf86b0b58d9.json
[
  {
    "address": "0xded0e76f559e39ff5dff607b0d58dcf86b0b58d9",
    "pick": "1849",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0xded0e76f559e39ff5dff607b0d58dcf86b0b58d9",
    "pick": "1857",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xded0e76f559e39ff5dff607b0d58dcf86b0b58d9",
    "pick": "8010",
    "tier": 6,
    "amount": "999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/84/0xadc12cc6a97a81c656bcdedfaf6bbd16a36cb9b3.json
[
  {
    "address": "0xadc12cc6a97a81c656bcdedfaf6bbd16a36cb9b3",
    "pick": "1426",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xadc12cc6a97a81c656bcdedfaf6bbd16a36cb9b3",
    "pick": "2505",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xadc12cc6a97a81c656bcdedfaf6bbd16a36cb9b3",
    "pick": "2964",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xadc12cc6a97a81c656bcdedfaf6bbd16a36cb9b3",
    "pick": "5430",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xadc12cc6a97a81c656bcdedfaf6bbd16a36cb9b3",
    "pick": "7845",
    "tier": 6,
    "amount": "999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/1/0xf756e4368a03627eac9b0c474c8420794f429ba1.json
[
  {
    "address": "0xf756e4368a03627eac9b0c474c8420794f429ba1",
    "pick": "2700",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0xf756e4368a03627eac9b0c474c8420794f429ba1",
    "pick": "4229",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0xf756e4368a03627eac9b0c474c8420794f429ba1",
    "pick": "4266",
    "tier": 5,
    "amount": "9999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/84/0x7e784506087d8336e34223b0ca998aa6f666fb39.json
[
  {
    "address": "0x7e784506087d8336e34223b0ca998aa6f666fb39",
    "pick": "2702",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0x7e784506087d8336e34223b0ca998aa6f666fb39",
    "pick": "9327",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x7e784506087d8336e34223b0ca998aa6f666fb39",
    "pick": "9526",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x7e784506087d8336e34223b0ca998aa6f666fb39",
    "pick": "9764",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0x7e784506087d8336e34223b0ca998aa6f666fb39",
    "pick": "22407",
    "tier": 6,
    "amount": "999999"
  }
]
