=== pooltogether/v4-draw-results/prize.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://pooltogether.com/prizeAPI.schema.json",
  "title": "PoolTogethers Prize API Schema",
  "description": "Schema for the Prize API",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "address": {
      "type": "string",
      "description": "The lowercase users address",
      "length": 42,
      "examples": ["0xa5c3a513645a9a00cb561fed40438e9dfe0d6a69"]
    },
    "pick": {
      "type": "string",
      "description": "The user's pick for this prize",
      "minLength": 1,
      "maxLength": 42
    },
    "tier": {
      "type": "number",
      "description": "The prize tier of this prize"
    },
    "amount": {
      "type": "string",
      "description": "The amount of the prize",
      "minLength": 1,
      "maxLength": 42
    }
  },
  "required": ["address", "pick", "tier", "amount"]
}

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/84/0xc6bf9a296f7477a45c660d692362b4f4c72d76a1.json
[
  {
    "address": "0xc6bf9a296f7477a45c660d692362b4f4c72d76a1",
    "pick": "3936",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xc6bf9a296f7477a45c660d692362b4f4c72d76a1",
    "pick": "5722",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xc6bf9a296f7477a45c660d692362b4f4c72d76a1",
    "pick": "5976",
    "tier": 6,
    "amount": "999999"
  },
  {
    "address": "0xc6bf9a296f7477a45c660d692362b4f4c72d76a1",
    "pick": "6808",
    "tier": 6,
    "amount": "999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/111/0x0acaa7e46a164d1b371326416b2d555cb13faa28.json
[
  {
    "address": "0x0acaa7e46a164d1b371326416b2d555cb13faa28",
    "pick": "825",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x0acaa7e46a164d1b371326416b2d555cb13faa28",
    "pick": "5040",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0x0acaa7e46a164d1b371326416b2d555cb13faa28",
    "pick": "7158",
    "tier": 5,
    "amount": "4999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/112/0xcfd92e7ec4733e428a34b9ae10f1dc0fe15c92fa.json
[
  {
    "address": "0xcfd92e7ec4733e428a34b9ae10f1dc0fe15c92fa",
    "pick": "3454",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0xcfd92e7ec4733e428a34b9ae10f1dc0fe15c92fa",
    "pick": "4058",
    "tier": 5,
    "amount": "4999999"
  },
  {
    "address": "0xcfd92e7ec4733e428a34b9ae10f1dc0fe15c92fa",
    "pick": "5863",
    "tier": 4,
    "amount": "9999999"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/252/0x0e9dd59448f53fa240dfd7a217f58d4d5efaff16.json
[
  {
    "address": "0x0e9dd59448f53fa240dfd7a217f58d4d5efaff16",
    "pick": "1098",
    "tier": 4,
    "amount": "4999999"
  },
  {
    "address": "0x0e9dd59448f53fa240dfd7a217f58d4d5efaff16",
    "pick": "14332",
    "tier": 4,
    "amount": "4999999"
  },
  {
    "address": "0x0e9dd59448f53fa240dfd7a217f58d4d5efaff16",
    "pick": "35144",
    "tier": 5,
    "amount": "5000000"
  }
]

=== pooltogether/v4-draw-results/api/prizes/137/0x8141bcfbcee654c5de17c4e2b2af26b67f9b9056/draw/15/0xc8f88b4aef57ac93fe41390194c3a4d77d7df744.json
[
  {
    "address": "0xc8f88b4aef57ac93fe41390194c3a4d77d7df744",
    "pick": "1334",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0xc8f88b4aef57ac93fe41390194c3a4d77d7df744",
    "pick": "5837",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0xc8f88b4aef57ac93fe41390194c3a4d77d7df744",
    "pick": "6122",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0xc8f88b4aef57ac93fe41390194c3a4d77d7df744",
    "pick": "6890",
    "tier": 5,
    "amount": "9999999"
  },
  {
    "address": "0xc8f88b4aef57ac93fe41390194c3a4d77d7df744",
    "pick": "7254",
    "tier": 5,
    "amount": "9999999"
  }
]
